baseURL = 'https://orelvis15.github.io/pool'
languageCode = 'es-es'
title = 'Ore pool web'
theme = 'theme'
logo='/logo'

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Acerca de mí"
    url = "/about"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[params]
  logo = "logo.png"

[params.footer]
  text = "by Orelvis Lago"
  url = "https://github.com/orelvis15"